### ISSUE TITLE
Some questions about architecture!

### ISSUE THREAD

**Issue by hamed-shirbandi** [armanleft/MonolithicDDD#1]
Hi dear @armanleft .
Thanks for sharing your knowledge with us.
I have some questions and like to know your answeres.

1. Can you explain your idea about placing facade service in presentation? don't you think it is a part of application ?

2. What is the diference if we use application services instead of facad in your architecture?

3. I think the 'Layer' suffix in folders name can be deleted by a PR from me 😁

I realy like to see some more chalenges with your architecture so maybe you want to upgrade your domain models.

I'll wait for it 😋

**Comment by armanleft** [comment]
Hello Hamed, Thank you for review.
1. It is not Facade it is FacadeGateway, and it's duty is:
Gateway provides a simple view of external resources to the internals of an application. So it will create necessary commands (nor just one command ) for the application service, checking command validation will be place here.
Facade provides a simple uniform view of complex internals to (one or more) external clients, So in read side of this project (as we will stick to CQRS), after calling repositories, the results will be merge in a simple DTO here.
These duties are not belong to Application.
2. The difference is about the SRP (Single Responsibility) and Dependencies between the layers. You can merge the responsibilities, and it will work with for you as we can merge Domain in Application!
3. That will be great of you, but I changed the project reference from .net 5 to .net 6 as it is LTS.
